### ISSUE TITLE
Compatibility with wireless module (bm.tx, rz.txt etc)

### ISSUE THREAD

**Issue by vv3** [roguenorman/bmpi#1]
The web ui should include endpoints which mimics the basic HTTP responses on the original wireless module (bm.txt, rz.txt, etc)

This will allow other software like the [speidel-ui](http://vesterheim.no/speidel-ui), [(source)](https://gitlab.com/vegard.vesterheim/speidel-ui) the [speidel-control](http://vesterheim.no/speidel-control) [(source)](https://gitlab.com/vegard.vesterheim/speidel-control) work unmodified without requiring a Wireless module.

I will try to implement this myself if I can get the basic functions working, serial port cable, serial communications (AT-commands) etc.

**Comment by vv3** [comment]
Looking at the source code, it seems that this issue can be closed.

**Comment by vv3** [comment]
I have now gotten the basic functions working, I simply needed to [add a few minor fixes](https://github.com/vv3/bmpi/tree/getting_it_working). I now realize that my Issue still is relevant, so I reopen it here. To reiterate my point: the original speidel-control web-application can be used entirely "offline", ie. without a "cloud service". It is simply some HTML/Javascript files after all, they can even be loaded directly from the file system, without any web server. (There were a few bugs in the original Javascript code which made the UI quite fragile, but I have [fixed](https://gitlab.com/vegard.vesterheim/speidel-control/-/commit/6c94144931c37c8714963460f586a3b6d78c8585) a [few](https://gitlab.com/vegard.vesterheim/speidel-control/-/commit/186ec1fb986b47a187851aa968debd5ef9bd7102) of [these](https://gitlab.com/vegard.vesterheim/speidel-control/-/commit/fc7860a4e87c26d3ce7852d044332c1e250ce9dd))

So the web GUI can be used (almost) as is, all that is needed is to re-implement the basic HTTP functionality provided with the Wifi-module, `bm.txt`, `rz.txt` etc. Now that I have gotten the basic functions working, this should be fairly trivial. I will take a stab at this at some point.

**Comment by vv3** [comment]
I have now implemented this in my fork here: https://github.com/vv3/bmpi/tree/getting_it_working

**Comment by HVR88** [comment]
@vv3 Why does this project reference the USB-serial adapter when it's using an RPi?

**Comment by vv3** [comment]
> [@vv3](https://github.com/vv3) Why does this project reference the USB-serial adapter when it's using an RPi?

The USB-serial adapter is not necessary when using an RPi, only when using an ordinary PC

**Comment by HVR88** [comment]
> > [@vv3](https://github.com/vv3) 
> 
> The USB-serial adapter is not necessary when using an RPi, only when using an ordinary PC

Can your fork also run solely on RPi?

It's not very clear here in the original repo if this project is able to replace/replicate all the features of the original WiFi module. I understand your fork allows recipe upload, however does it work exclusively as an alternative to using the original module or does it mimic/replicate the original so that the controller thinks it's the real thing when connected?

**Comment by vv3** [comment]
> Can your fork also run solely on RPi?

Yes

> It's not very clear here in the original repo if this project is able to replace/replicate all the features of the original WiFi module. I understand your fork allows recipe upload, however does it work exclusively as an alternative to using the original module or does it mimic/replicate the original so that the controller thinks it's the real thing when connected?

Unsure about some of your questions. It has been a while since I worked on this. I do not have complete knowledge about the features of the original WiFi module. Currently I am observing some performance problems, seemingly related to the serial communication.

**Comment by roguenorman** [comment]
> > > [@vv3](https://github.com/vv3)
> > 
> > 
> > The USB-serial adapter is not necessary when using an RPi, only when using an ordinary PC
> 
> Can your fork also run solely on RPi?
> 
> It's not very clear here in the original repo if this project is able to replace/replicate all the features of the original WiFi module. I understand your fork allows recipe upload, however does it work exclusively as an alternative to using the original module or does it mimic/replicate the original so that the controller thinks it's the real thing when connected?

I have not touched this in years so my memory is fuzzy. The only way to initiate the connection to the BM is to send the same paylaods that the wifi controller does. so in that respect, the BM thinks its connecetd to the real thing. 

it doesnt have the same functionality as the wifi controller as i never really got around to doing it. The way that it decodes the responses from the BM sucks. I wanted to see whether I can use HTTP HEAD and/or use the content-length to know when the http response was complete so the performance was better, but i never got around to it.
